after review
romilMasnaviev/java-filmorate pull request #3
Opened 2023-10-06 17:34 UTC by romilMasnaviev

2023-10-06 17:45 UTC, romilMasnaviev commented
К сожалению, пришлось пересоздавать репозиторий

замечания были следующие :
1) вынести общие части - вынес в FilmorateStorage
2) в методах validateUser и validateFilm выводить пользователю в чем была ошибка
3) были пустые checks - исправил ( из-за этого и пришлось сносить полностью репозиторий)

2023-10-07 15:52 UTC, ErkinKasymaliev requested changes
привет, оставил коммент

2023-10-07 15:52 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmorateStorage.java
> +public class FilmorateStorage {
это зачем? он не нужен, верните как было
я имел ввиду вынести только  protected final Gson gson = new GsonBuilder().registerTypeAdapter(LocalDate.class, new LocalDateAdapter()).create();

2023-10-07 15:53 UTC, ErkinKasymaliev commented
> К сожалению, пришлось пересоздавать репозиторий
> 
> замечания были следующие :
> 
> 1. вынести общие части - вынес в FilmorateStorage
> 2. в методах validateUser и validateFilm выводить пользователю в чем была ошибка
> 3. были пустые checks - исправил ( из-за этого и пришлось сносить полностью репозиторий)

1. оставил еще коммент
2. не ошибка, это как предложение было - добавить валидационные аннотации
3. отлично

2023-10-08 08:20 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-10-08 08:20 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/util/GsonUtil.java
> +    private static final com.google.gson.Gson gson = new GsonBuilder().registerTypeAdapter(LocalDate.class, new LocalDateAdapter()).create();
отлично!

2023-10-11 13:35 UTC, merged