Add friends likes
romilMasnaviev/java-filmorate pull request #4
Opened 2023-10-19 16:57 UTC by romilMasnaviev

2023-10-20 07:45 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2023-10-20 07:45 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired
вместо этого можно просто поставить над классом аннотацию @RequiredArgsConstructor - он заменяет конструктор и аннотацию @Autowired над ним

2023-10-20 07:45 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @Autowired
вместо этого можно просто поставить над классом аннотацию @requiredargsconstructor - он заменяет конструктор и аннотацию @Autowired над ним

2023-10-20 07:45 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    @Autowired
вместо этого можно просто поставить над классом аннотацию @requiredargsconstructor - он заменяет конструктор и аннотацию @Autowired над ним

2023-10-20 07:45 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage storage;
здесь только private final FilmService service; storage вызываетеся у вас в service

2023-10-20 07:45 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final UserStorage storage;
здесь только private final UserService service; storage вызываетеся у вас в service

2023-10-20 07:45 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +
а где методы getById(), getAllFilms(), add(), update()?

2023-10-20 07:45 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            throw new NotFoundException("wrong friend id");
тут ValidationException должен быть

2023-10-20 07:45 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        } else throw new ValidationException("Some of the friends are not there");
а тут NotFound

2023-10-20 07:45 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +
а где методы getById(), getAllFilms(), add(), update()?

2023-10-20 15:20 UTC, romilMasnaviev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            throw new NotFoundException("wrong friend id");
Здесь не 400 не проходит по тестам, в ТЗ сказано: 404 — для всех ситуаций, если искомый объект не найден

2023-10-21 05:37 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            throw new NotFoundException("wrong friend id");
ну так тут вы валидацию входных аргументов же проверяете до вызова getFriends()

2023-10-21 05:42 UTC, ErkinKasymaliev requested changes
привет, еще пару комментов оставил

2023-10-21 05:42 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        return null;
реализуйте метод

2023-10-21 05:42 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public Film addFilm(Film film) {
поставьте на имплементируемыми методами @Override

2023-10-21 05:42 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    public User addUser(User user) {
поставьте на имплементируемыми методами @Override

2023-10-21 08:51 UTC, romilMasnaviev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            throw new NotFoundException("wrong friend id");
Я могу исправить это, но тогда тесты не будут проходить

2023-10-21 12:23 UTC, ErkinKasymaliev approved these changes
работа принята

2023-10-21 14:25 UTC, merged