Add database
romilMasnaviev/java-filmorate pull request #5
Opened 2023-11-19 22:48 UTC by romilMasnaviev

2023-11-20 07:43 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2023-11-20 07:43 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public List<User> getSameFriends(@PathVariable int id, @PathVariable int otherId) {
а почему поменяли?

2023-11-20 07:43 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private List<Genre> genres;
наверно лучше Set чтобы дубликатов не было

2023-11-20 07:43 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            film.setGenres(genreStorage.getFilmsGenres(film.getId()));
а если будет в коллекции 100 фильмов, то тут будет 100 дополнительных запросов? getPopular - это запрос измените, добавив join с таблицей жанров

2023-11-20 07:43 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            film.setGenres(genreStorage.getFilmsGenres(film.getId()));
смотрите коммент выше

2023-11-20 07:43 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Genre getGenre(int genreId) {
сделайте отдельный сервис для жанров

2023-11-20 07:43 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Mpa getMpa(int id) {
отдельный сервис для mpa

2023-11-20 07:43 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            friends.add(userStorage.getUser(friendId));
опять же - это допоолнительные N запросов, где N кол-во друзей. Добавьте join-ы сюда friendStorage.getFriendsList(id)

2023-11-20 07:43 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        for (Integer friendId : friendsId) {
выше коммент смотрите

2023-11-20 07:43 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +            String sqlSelect = "SELECT TOP 1 film_id FROM films ORDER BY film_id DESC";
я не помню, как, но есть способ вот здесь dbcTemplate.update схендлить сгенерированный id. Возможно наставник вам это показывал. Попробуйте сделать так и не использовать дополнительный селект после insert

2023-11-20 07:43 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private List<Genre> genres;
рекомендательный коммент

2023-11-20 07:57 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +            String sqlSelect = "SELECT TOP 1 film_id FROM films ORDER BY film_id DESC";
примерно так:
```
public Film create(Film film) {         
    SimpleJdbcInsert simpleJdbcInsert = new SimpleJdbcInsert(jdbcTemplate)                 
         .withTableName("films")                
         .usingGeneratedKeyColumns("id");         
    int filmId = simpleJdbcInsert.executeAndReturnKey(filmMap(film)).intValue();        
    return getById(filmId);     
}
```

2023-11-20 17:25 UTC, romilMasnaviev commented
> привет, оставил комменты

Сложно было справится с рейтингами ( получением сразу фильмов и списка жанров для них). Поэтому сделал более общие запросы к бд, и собирал объект Фильма уже в сервисе

2023-11-21 03:42 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2023-11-21 03:42 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +        return jdbcTemplate.query(sql, (rs, rowNum) -> Film.builder().id(rs.getInt("film_id")).name(rs.getString("film_name")).releaseDate(rs.getDate("film_release_date").toLocalDate()).description(r
rs.getInt("film_mpa_id"), rate(rs.getInt("film_rate") - ок, вы сеттите id map и id rating. Но мне как пользователю эти данные ни о чем не говорят - мне нужны как минимум их названия. Поэтому я и написал переписать через join-запросы

2023-11-21 03:42 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FriendDbStorage.java
> +        return jdbcTemplate.query(sqlGetId, new Object[]{id}, (rs, rowNum) -> User.builder().id(rs.getInt("user_id")).email(rs.getString("user_email")).login(rs.getString("user_login")).name(rs.getSt
User.builder().id(rs.getInt("user_id")).email(rs.getString("user_email")).login(rs.getString("user_login")).name(rs.getString("user_name")).birthday(rs.getDate("user_birthday").toLocalDate()).friendsId(getFriendsIds(rs.getInt("user_id"))).build());
    } -- уберите в отдельный метод

2023-11-21 03:42 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +        return jdbcTemplate.query(sql, (rs, rowNum) -> Film.builder().id(rs.getInt("film_id")).name(rs.getString("film_name")).releaseDate(rs.getDate("film_release_date").toLocalDate()).description(r
Film.builder().id(rs.getInt("film_id")).name(rs.getString("film_name")).releaseDate(rs.getDate("film_release_date").toLocalDate()).description(rs.getString("film_description")).duration(rs.getInt("film_duration")).rate(rs.getInt("film_rate")).mpa(Mpa.builder().id(rs.getInt("film_mpa_id")).build()).build()); -- зачем его писать -- он же у вас в приватном методе

2023-11-21 05:58 UTC, romilMasnaviev commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +        return jdbcTemplate.query(sql, (rs, rowNum) -> Film.builder().id(rs.getInt("film_id")).name(rs.getString("film_name")).releaseDate(rs.getDate("film_release_date").toLocalDate()).description(r
Понял. У меня возникли проблемы с архитектурой приложения, и честно говоря, в коде каша получилась. Я хочу сдать работу и переделать саму архитектуру ( во всех Storage  у меня не реализован CRUD явно, к сожалению). Этот метод вообще нигде не используется.

2023-11-21 06:07 UTC, romilMasnaviev commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +        return jdbcTemplate.query(sql, (rs, rowNum) -> Film.builder().id(rs.getInt("film_id")).name(rs.getString("film_name")).releaseDate(rs.getDate("film_release_date").toLocalDate()).description(r
Если не сложно, можете, пожалуйста сказать, как делать лучше?
Например метод getPopular в likeDbStorage должен сразу выдавать готовый результат, обращаясь ко всем базам данных, или все таки необходимо обогащать данные на уровне сервиса, где собраны остальные Storage? 
Первый подход ставит под вопрос необходимость CRUD, так как мы просто для каждого метода пишем конкретный запрос.
Второй ( по моему мнению) позволяет пользоваться элементарными операциями, но тогда получается как при первом ревью, что слишком много запросов

Или лучше реализовать оба подхода и создать базовые методы CRUD и дополнить их специфичными требованиями? 
Спасибо заранее

2023-11-21 09:17 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +        return jdbcTemplate.query(sql, (rs, rowNum) -> Film.builder().id(rs.getInt("film_id")).name(rs.getString("film_name")).releaseDate(rs.getDate("film_release_date").toLocalDate()).description(r
SELECT f.*, m.*, g.* FROM films f
join mpa m on m.id=f.mpa_id
join genres g on g.id = f.genre_id

это запрос вам вернет film, рейтинг, жанры - там уже засетите в объект Film все

2023-11-21 11:28 UTC, ErkinKasymaliev approved these changes
привет, работа принята!

2023-11-27 06:11 UTC, merged